name = "JuNEI"
uuid = "682ec16d-bad4-47d0-b0ae-38dcf160f772"
authors = ["ARCJ137442"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
